### ISSUE TITLE
您好！训练至少需要多少张图片和一些补充问题

### ISSUE THREAD

**Issue by xiawei20161308104** [bubbliiiing/clip-pytorch#11]
我是医疗数据集，目前有440张，并且每个img只对应一条caption。请问
1，这种数据集情况下，是不是会影响效果？
2，如果是因为数据集导致的效果不好，医疗方向病例并不会很多，有什么改进办法吗？
3，有什么在医疗影像上微调的CLIP预训练权重推荐吗？

万分感谢！！

**Comment by A0268** [comment]
您好，我目前的情况和您一样，请问有什么解决办法吗，谢谢！
